# Generated by Django 2.2.6 on 2019-10-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Email',
            field=models.EmailField(default='none@gmail.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
