# Generated by Django 2.2.6 on 2019-10-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20191018_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='Age',
        ),
    ]
