# Generated by Django 2.2.6 on 2019-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='user_details',
            name='Deep_Cuts',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Diagnosed_with_Malaria',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Diagnosed_with_Typhoid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Sickel_cell',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Tuberculosis',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Email',
            field=models.EmailField(default='none@email.com', max_length=254),
        ),
    ]
