# Generated by Django 2.2.6 on 2019-10-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_user_details_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user_details')),
            ],
        ),
    ]
