# Generated by Django 2.2.6 on 2019-10-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='content',
        ),
    ]
